import React from 'react';
import Navbar from "../Navbar/Navbar";

const Apropos = () => {
  return (
    <div className="apropos-container">
      <Navbar />
      <div className="apropos-content">
        <h1>À propos de notre projet de gestion de parkings</h1>
        <p>
        Maecenas sagittis est ex, vitae fringilla ex tincidunt at. Donec consequat vulputate nisl, a eleifend lectus laoreet ut. Etiam molestie orci ex, aliquam scelerisque neque hendrerit sed. Curabitur a dui in tortor porttitor consectetur. Phasellus molestie sapien id scelerisque pharetra. Nunc nec dolor non justo pellentesque luctus. Mauris pulvinar dapibus turpis, nec maximus sem consectetur sed. In et rhoncus risus, ut bibendum justo. Vestibulum venenatis tortor nisi, vel faucibus nulla tincidunt a. Morbi finibus fermentum varius.

Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Sed ut placerat nunc. Fusce rhoncus, magna vitae mollis gravida, ex enim euismod purus, id porttitor eros tellus vel nibh. Mauris hendrerit sem in odio imperdiet, a lobortis metus mattis. Ut sed egestas lorem, eget dictum ante. Aenean et tempus risus, sit amet auctor nisl. Donec finibus, sapien non volutpat pharetra, est arcu dictum dolor, vel maximus elit orci vel metus. Nam ut cursus mauris. Vestibulum in hendrerit magna. Vivamus nunc neque, pellentesque sit amet justo in, sagittis vestibulum magna. Vestibulum sollicitudin, tortor sed consequat pellentesque, ligula magna posuere tortor, tristique congue dolor turpis non nunc.

Aenean at diam vel sapien molestie feugiat ac non dui. In sem sem, mollis quis lacus quis, blandit maximus sapien. Pellentesque gravida nisi ipsum, non suscipit tellus vehicula quis. Morbi at massa venenatis, dictum justo ut, fermentum sem. Aliquam a velit sed neque mattis aliquam et ac odio. Suspendisse pulvinar ligula vitae diam rhoncus condimentum. Duis placerat, sapien non dapibus efficitur, felis lectus malesuada nulla, id sollicitudin diam mi vel ex. Maecenas metus lacus, commodo eu ex et, facilisis condimentum dui. Sed sit amet viverra nunc. Maecenas a est neque.

Donec urna ex, eleifend a eros a, volutpat maximus erat. Cras posuere dictum ligula id dignissim. Etiam sollicitudin, tellus id fringilla dictum, augue augue lacinia purus, sed pretium ipsum ex ut sapien. Cras quis mattis lectus, sit amet dictum elit. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Ut in arcu at ex porttitor porta. Morbi rhoncus bibendum libero sit amet consectetur. Quisque varius tortor quis sagittis mollis. Duis feugiat ullamcorper ipsum vel rutrum. Curabitur vel fermentum nisl. Aliquam pretium vulputate hendrerit. Maecenas nibh risus, maximus id vestibulum non, porta quis augue. Ut pulvinar ipsum ac dignissim finibus. In rhoncus, urna at finibus molestie, ligula mi lacinia felis, non cursus dolor ligula vel enim.

Sed nec ornare ligula. Donec luctus felis vitae facilisis rutrum. Ut et egestas mauris, id sodales magna. Donec vel arcu lobortis, maximus risus quis, fringilla turpis. Phasellus sit amet nisi tellus. Praesent tempus vel ligula tristique tincidunt. Vestibulum enim justo, viverra at risus sit amet, finibus egestas risus. Aliquam efficitur dui felis, nec facilisis leo maximus et. Nulla eget nisi enim. Donec lacinia, erat ac pulvinar hendrerit, ipsum metus faucibus ex, laoreet fermentum urna quam et nunc. Maecenas fringilla libero et nibh efficitur, imperdiet pellentesque nulla luctus. Nunc elementum lacus non turpis consectetur, et convallis dolor elementum. Nam laoreet eu massa a porttitor. In rhoncus mi eget iaculis aliquam. Donec sed magna eget odio iaculis gravida.
        </p>
        <p>
        Maecenas sagittis est ex, vitae fringilla ex tincidunt at. Donec consequat vulputate nisl, a eleifend lectus laoreet ut. Etiam molestie orci ex, aliquam scelerisque neque hendrerit sed. Curabitur a dui in tortor porttitor consectetur. Phasellus molestie sapien id scelerisque pharetra. Nunc nec dolor non justo pellentesque luctus. Mauris pulvinar dapibus turpis, nec maximus sem consectetur sed. In et rhoncus risus, ut bibendum justo. Vestibulum venenatis tortor nisi, vel faucibus nulla tincidunt a. Morbi finibus fermentum varius.

Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Sed ut placerat nunc. Fusce rhoncus, magna vitae mollis gravida, ex enim euismod purus, id porttitor eros tellus vel nibh. Mauris hendrerit sem in odio imperdiet, a lobortis metus mattis. Ut sed egestas lorem, eget dictum ante. Aenean et tempus risus, sit amet auctor nisl. Donec finibus, sapien non volutpat pharetra, est arcu dictum dolor, vel maximus elit orci vel metus. Nam ut cursus mauris. Vestibulum in hendrerit magna. Vivamus nunc neque, pellentesque sit amet justo in, sagittis vestibulum magna. Vestibulum sollicitudin, tortor sed consequat pellentesque, ligula magna posuere tortor, tristique congue dolor turpis non nunc.

Aenean at diam vel sapien molestie feugiat ac non dui. In sem sem, mollis quis lacus quis, blandit maximus sapien. Pellentesque gravida nisi ipsum, non suscipit tellus vehicula quis. Morbi at massa venenatis, dictum justo ut, fermentum sem. Aliquam a velit sed neque mattis aliquam et ac odio. Suspendisse pulvinar ligula vitae diam rhoncus condimentum. Duis placerat, sapien non dapibus efficitur, felis lectus malesuada nulla, id sollicitudin diam mi vel ex. Maecenas metus lacus, commodo eu ex et, facilisis condimentum dui. Sed sit amet viverra nunc. Maecenas a est neque.

Donec urna ex, eleifend a eros a, volutpat maximus erat. Cras posuere dictum ligula id dignissim. Etiam sollicitudin, tellus id fringilla dictum, augue augue lacinia purus, sed pretium ipsum ex ut sapien. Cras quis mattis lectus, sit amet dictum elit. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Ut in arcu at ex porttitor porta. Morbi rhoncus bibendum libero sit amet consectetur. Quisque varius tortor quis sagittis mollis. Duis feugiat ullamcorper ipsum vel rutrum. Curabitur vel fermentum nisl. Aliquam pretium vulputate hendrerit. Maecenas nibh risus, maximus id vestibulum non, porta quis augue. Ut pulvinar ipsum ac dignissim finibus. In rhoncus, urna at finibus molestie, ligula mi lacinia felis, non cursus dolor ligula vel enim.

Sed nec ornare ligula. Donec luctus felis vitae facilisis rutrum. Ut et egestas mauris, id sodales magna. Donec vel arcu lobortis, maximus risus quis, fringilla turpis. Phasellus sit amet nisi tellus. Praesent tempus vel ligula tristique tincidunt. Vestibulum enim justo, viverra at risus sit amet, finibus egestas risus. Aliquam efficitur dui felis, nec facilisis leo maximus et. Nulla eget nisi enim. Donec lacinia, erat ac pulvinar hendrerit, ipsum metus faucibus ex, laoreet fermentum urna quam et nunc. Maecenas fringilla libero et nibh efficitur, imperdiet pellentesque nulla luctus. Nunc elementum lacus non turpis consectetur, et convallis dolor elementum. Nam laoreet eu massa a porttitor. In rhoncus mi eget iaculis aliquam. Donec sed magna eget odio iaculis gravida.
        </p>
        <p>
        Maecenas sagittis est ex, vitae fringilla ex tincidunt at. Donec consequat vulputate nisl, a eleifend lectus laoreet ut. Etiam molestie orci ex, aliquam scelerisque neque hendrerit sed. Curabitur a dui in tortor porttitor consectetur. Phasellus molestie sapien id scelerisque pharetra. Nunc nec dolor non justo pellentesque luctus. Mauris pulvinar dapibus turpis, nec maximus sem consectetur sed. In et rhoncus risus, ut bibendum justo. Vestibulum venenatis tortor nisi, vel faucibus nulla tincidunt a. Morbi finibus fermentum varius.

Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Sed ut placerat nunc. Fusce rhoncus, magna vitae mollis gravida, ex enim euismod purus, id porttitor eros tellus vel nibh. Mauris hendrerit sem in odio imperdiet, a lobortis metus mattis. Ut sed egestas lorem, eget dictum ante. Aenean et tempus risus, sit amet auctor nisl. Donec finibus, sapien non volutpat pharetra, est arcu dictum dolor, vel maximus elit orci vel metus. Nam ut cursus mauris. Vestibulum in hendrerit magna. Vivamus nunc neque, pellentesque sit amet justo in, sagittis vestibulum magna. Vestibulum sollicitudin, tortor sed consequat pellentesque, ligula magna posuere tortor, tristique congue dolor turpis non nunc.

Aenean at diam vel sapien molestie feugiat ac non dui. In sem sem, mollis quis lacus quis, blandit maximus sapien. Pellentesque gravida nisi ipsum, non suscipit tellus vehicula quis. Morbi at massa venenatis, dictum justo ut, fermentum sem. Aliquam a velit sed neque mattis aliquam et ac odio. Suspendisse pulvinar ligula vitae diam rhoncus condimentum. Duis placerat, sapien non dapibus efficitur, felis lectus malesuada nulla, id sollicitudin diam mi vel ex. Maecenas metus lacus, commodo eu ex et, facilisis condimentum dui. Sed sit amet viverra nunc. Maecenas a est neque.

Donec urna ex, eleifend a eros a, volutpat maximus erat. Cras posuere dictum ligula id dignissim. Etiam sollicitudin, tellus id fringilla dictum, augue augue lacinia purus, sed pretium ipsum ex ut sapien. Cras quis mattis lectus, sit amet dictum elit. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Ut in arcu at ex porttitor porta. Morbi rhoncus bibendum libero sit amet consectetur. Quisque varius tortor quis sagittis mollis. Duis feugiat ullamcorper ipsum vel rutrum. Curabitur vel fermentum nisl. Aliquam pretium vulputate hendrerit. Maecenas nibh risus, maximus id vestibulum non, porta quis augue. Ut pulvinar ipsum ac dignissim finibus. In rhoncus, urna at finibus molestie, ligula mi lacinia felis, non cursus dolor ligula vel enim.

Sed nec ornare ligula. Donec luctus felis vitae facilisis rutrum. Ut et egestas mauris, id sodales magna. Donec vel arcu lobortis, maximus risus quis, fringilla turpis. Phasellus sit amet nisi tellus. Praesent tempus vel ligula tristique tincidunt. Vestibulum enim justo, viverra at risus sit amet, finibus egestas risus. Aliquam efficitur dui felis, nec facilisis leo maximus et. Nulla eget nisi enim. Donec lacinia, erat ac pulvinar hendrerit, ipsum metus faucibus ex, laoreet fermentum urna quam et nunc. Maecenas fringilla libero et nibh efficitur, imperdiet pellentesque nulla luctus. Nunc elementum lacus non turpis consectetur, et convallis dolor elementum. Nam laoreet eu massa a porttitor. In rhoncus mi eget iaculis aliquam. Donec sed magna eget odio iaculis gravida.
        </p>
      </div>
    </div>
  );
}

export default Apropos;
